# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_as_errors: false

os:
  - linux
  - osx

r:
  - 3.3
  - 3.4
  - oldrel
  - release
  - devel